Add a codepage test. (#2856)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -347,6 +347,37 @@ jobs:
         run: |
           strip -s build/host/sdk/bin/*
 
+      # For some reason this test must run before we call 'make test' and 'make test-health'.
+      - name: Test Windows code pages
+        if: env.DO_TESTS == 'true' && runner.os == 'Windows' && matrix.shard == 1
+        shell: pwsh
+        run: |
+          # Run the test script which creates a directory with Thai characters
+          # (using code page 874) and runs Toit inside it.
+          cmd.exe /c tests\test-cp874.cmd
+
+          # Read and check output.
+          $outputContent = Get-Content -Path "output.txt" -Raw
+          Write-Host $outputContent
+          if (-not ($outputContent -match "hello")) {
+            Write-Error "Test failed: 'hello' not found in output"
+            exit 1
+          }
+
+          # Now run Toit from inside the directory (to test the CWD).
+          cd 'เดสก์ท็อป'
+          cmd.exe /c "chcp 874 && ..\build\host\sdk\bin\toit run main.toit > ../output_inside.txt"
+          cd ..
+          $insideContent = Get-Content -Path "output_inside.txt" -Raw
+          Write-Host $insideContent
+          if (-not ($insideContent -match "hello")) {
+            Write-Error "Test failed: 'hello' not found in output_inside"
+            exit 1
+          }
+
+          # Clean up.
+          Remove-Item -Recurse -Force 'เดสก์ท็อป'
+
       # Test.
       - name: Test
         if: env.DO_TESTS == 'true'
@@ -839,7 +870,7 @@ jobs:
       - name: Set up macOS ARM environment
         run: |
           if [[ "${{ env.DO_RELEASE }}" == 'true' || \
-                "${{ env.BUILD_ARM_MACOS }}" == 'true' || \
+                "${{ env.BUILD_ARM_MACOS }}" == "true" || \
                 "${{ github.ref }}" == 'refs/heads/master' \
               ]]; then
             echo "MACOS_ARM=macos-arm" >> $GITHUB_ENV;
